$('.dianji').on('click',function(){
    $('.xb-grow').addClass('quxiao')
    $('.shang-tab').removeClass('quxiao')
    $('.shang-tab1').addClass('quxiao')
})
$('.dianji1').on('click',function(){
    $('.xb-grow').removeClass('quxiao')
    $('.shang-tab').addClass('quxiao')
    $('.shang-tab1').addClass('quxiao')
})
$('.dianji2').on('click',function(){
    $('.xb-grow').addClass('quxiao')
    $('.shang-tab').addClass('quxiao')
    $('.shang-tab1').removeClass('quxiao')
})
